#!/usr/bin/python3
import tkinter as tk
import tkinter.ttk as ttk


class aUI:
    def __init__(self, master=None):
        # build ui
        tk2 = tk.Tk(master)
        tk2.configure(height=720, width=1280)
        frame3 = ttk.Frame(tk2)
        frame3.configure(height=180, width=320)
        message3 = tk.Message(frame3)
        message3.configure(text='Digite o IP do CLP', width=100)
        message3.pack(anchor="center", pady=20, side="top")
        entry7 = ttk.Entry(frame3)
        entry7.pack(anchor="center", side="top")
        button1 = ttk.Button(frame3)
        button1.configure(text='Conectar')
        button1.pack(anchor="center", pady=20, side="top")
        frame3.grid(column=0, row=0)
        frame3.pack_propagate(0)
        frame6 = ttk.Frame(tk2)
        frame6.configure(height=720, width=1280)
        labelframe2 = ttk.Labelframe(frame6)
        labelframe2.configure(
            height=200,
            text='Selecão de itens para cada caixa',
            width=200)
        label1 = tk.Label(labelframe2)
        label1.configure(text='Metalica Pequena')
        label1.grid(column=0, padx=20, pady=6, row=1)
        label2 = tk.Label(labelframe2)
        label2.configure(text='Metalica Media')
        label2.grid(column=0, row=2)
        label3 = tk.Label(labelframe2)
        label3.configure(text='Metalica Grande')
        label3.grid(column=0, pady=6, row=3)
        label4 = tk.Label(labelframe2)
        label4.configure(text='Nao metalica pequena')
        label4.grid(column=0, row=4)
        label5 = tk.Label(labelframe2)
        label5.configure(
            cursor="arrow",
            font="TkDefaultFont",
            text='Nao metalica media')
        label5.grid(column=0, pady=6, row=5)
        label6 = tk.Label(labelframe2)
        label6.configure(text='Nao metalica grande')
        label6.grid(column=0, row=6)
        label7 = tk.Label(labelframe2)
        label7.configure(text='Caixa de descarte 1')
        label7.grid(column=1, row=0)
        spinbox1 = tk.Spinbox(labelframe2)
        spinbox1.configure(width=6)
        spinbox1.grid(column=1, row=1)
        spinbox3 = tk.Spinbox(labelframe2)
        spinbox3.configure(width=6)
        spinbox3.grid(column=1, row=2)
        spinbox4 = tk.Spinbox(labelframe2)
        spinbox4.configure(width=6)
        spinbox4.grid(column=1, row=3)
        spinbox5 = tk.Spinbox(labelframe2)
        spinbox5.configure(width=6)
        spinbox5.grid(column=1, row=4)
        spinbox6 = tk.Spinbox(labelframe2)
        spinbox6.configure(width=6)
        spinbox6.grid(column=1, row=5)
        spinbox7 = tk.Spinbox(labelframe2)
        spinbox7.configure(width=6)
        spinbox7.grid(column=1, row=6)
        label8 = tk.Label(labelframe2)
        label8.configure(text='Caixa de descarte 2')
        label8.grid(column=2, padx=17, row=0)
        spinbox8 = tk.Spinbox(labelframe2)
        spinbox8.configure(width=6)
        spinbox8.grid(column=2, row=1)
        spinbox9 = tk.Spinbox(labelframe2)
        spinbox9.configure(width=6)
        spinbox9.grid(column=2, row=2)
        spinbox10 = tk.Spinbox(labelframe2)
        spinbox10.configure(width=6)
        spinbox10.grid(column=2, row=3)
        spinbox11 = tk.Spinbox(labelframe2)
        spinbox11.configure(width=6)
        spinbox11.grid(column=2, row=4)
        spinbox12 = tk.Spinbox(labelframe2)
        spinbox12.configure(width=6)
        spinbox12.grid(column=2, row=5)
        spinbox13 = tk.Spinbox(labelframe2)
        spinbox13.configure(width=6)
        spinbox13.grid(column=2, row=6)
        label9 = tk.Label(labelframe2)
        label9.configure(text='Caixa de descarte 3')
        label9.grid(column=3, row=0)
        spinbox14 = tk.Spinbox(labelframe2)
        spinbox14.configure(width=6)
        spinbox14.grid(column=3, row=1)
        spinbox15 = tk.Spinbox(labelframe2)
        spinbox15.configure(width=6)
        spinbox15.grid(column=3, row=2)
        spinbox16 = tk.Spinbox(labelframe2)
        spinbox16.configure(width=6)
        spinbox16.grid(column=3, row=3)
        spinbox17 = tk.Spinbox(labelframe2)
        spinbox17.configure(width=6)
        spinbox17.grid(column=3, row=4)
        spinbox18 = tk.Spinbox(labelframe2)
        spinbox18.configure(width=6)
        spinbox18.grid(column=3, row=5)
        spinbox19 = tk.Spinbox(labelframe2)
        spinbox19.configure(width=6)
        spinbox19.grid(column=3, row=6)
        labelframe2.grid(column=0, ipadx=5, ipady=5, row=1)
        frame10 = ttk.Frame(frame6)
        frame10.configure(height=300, width=500)
        canvas2 = tk.Canvas(frame10)
        canvas2.configure(height=450, width=1200)
        canvas2.pack(padx=15, pady=15, side="top")
        frame10.grid(column=0, row=0)
        frame6.grid(column=0, row=1)
        frame6.grid_propagate(0)
        frame6.grid_anchor("n")

        # Main widget
        self.mainwindow = tk2

    def run(self):
        self.mainwindow.mainloop()


if __name__ == "__main__":
    app = aUI()
    app.run()
